// AUTO-GENERATED by _build-images.mjs — do not edit by hand.
import type { SiteImage } from "@/data/images";

/** Photos shown in the gallery (everything not placed in a specific section). */
export const galleryImages: SiteImage[] = [
  {
    "src": "/images/gallery/exterior/dsc0703.webp",
    "alt": "Nonna Lodge and its grounds",
    "category": "exterior"
  },
  {
    "src": "/images/gallery/exterior/dsc0706.webp",
    "alt": "Nonna Lodge and its grounds",
    "category": "exterior"
  },
  {
    "src": "/images/gallery/exterior/dsc0710.webp",
    "alt": "Nonna Lodge and its grounds",
    "category": "exterior"
  },
  {
    "src": "/images/gallery/exterior/dsc0732.webp",
    "alt": "Nonna Lodge and its grounds",
    "category": "exterior"
  },
  {
    "src": "/images/gallery/exterior/dsc0881.webp",
    "alt": "Nonna Lodge and its grounds",
    "category": "exterior"
  },
  {
    "src": "/images/gallery/room/dsc0744.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0748.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0758.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0770.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0773.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0780.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0784.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0793.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0797.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0799.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0801.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0804.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0806.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0814.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0829.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0831.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0832.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0843.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0847.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0848.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0855.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0866.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0870.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0872.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/room/dsc0878.webp",
    "alt": "A guest room at Nonna Lodge",
    "category": "room"
  },
  {
    "src": "/images/gallery/dining/dsc0470.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0478.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0483.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0485.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0486.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0490.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0493.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0495.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0514.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0520.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0523.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0529.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0536.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0537.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0538.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0549.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0553.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0562.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0564.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0565.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0573.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0578.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0580.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0586.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0595.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0596.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0601.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0604.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0609.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0611.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0612.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0655.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0658.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0660.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0662.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0665.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0669.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0671.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0677.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0681.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0683.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0687.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0688.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0689.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0696.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0697.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0698.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0896.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0911.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0916.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0918.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0922.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0927.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0929.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0931.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/dining/dsc0934.webp",
    "alt": "Dining, food and drinks at Nonna Lodge",
    "category": "dining"
  },
  {
    "src": "/images/gallery/interior/dsc0602.webp",
    "alt": "Inside Nonna Lodge",
    "category": "interior"
  },
  {
    "src": "/images/gallery/interior/dsc0632.webp",
    "alt": "Inside Nonna Lodge",
    "category": "interior"
  },
  {
    "src": "/images/gallery/interior/dsc0637.webp",
    "alt": "Inside Nonna Lodge",
    "category": "interior"
  },
  {
    "src": "/images/gallery/interior/dsc0641.webp",
    "alt": "Inside Nonna Lodge",
    "category": "interior"
  },
  {
    "src": "/images/gallery/interior/dsc0643.webp",
    "alt": "Inside Nonna Lodge",
    "category": "interior"
  },
  {
    "src": "/images/gallery/interior/dsc0700.webp",
    "alt": "Inside Nonna Lodge",
    "category": "interior"
  },
  {
    "src": "/images/gallery/interior/dsc0825.webp",
    "alt": "Inside Nonna Lodge",
    "category": "interior"
  }
];
